language: node_js
node_js:
- "6"
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --27 5
- export PATH="$HOME/.yarn/bin:$PATH"
install:
- yarn
